#Here is where you define services in terms of ports and command line
#programs, this is just an example to start you off of a very simple
#service that serves hello world on two ports, load balanced
#and with failover
services:
  -
    port: 9000
    #having a proxy port hooks up nginx
    proxy_port: 9090
    #files ending in the following space separated patterns
    reload_on_changes:
      - rb
      - py
    programs:
      -
        port: 9001
        exec: .stew/hello 9001
      -
        port: 9002
        exec: .stew/hello 9002
    timeout: 30000
#you can also just put in long running programs, background jobs that don't
#serve a port to provide a service, but do local processing, things like
#watchr or redis
#programs:
#  -
#    name: <<just a string>>
#    exec: <<command line relative to your root>>
#and file event notification autocompilation support
autocompile: true
